version: 2.1
jobs:
  deploy_dev:
    circleci_ip_ranges: true
    docker:
      - image: circleci/python:3.8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "$SSH_KEY_FINGERPRINT"
      - run:
          name: Set up SSH
          command: |
            mkdir -p ~/.ssh
            echo "EC2_IP: $EC2_IP"
            ssh-keyscan -v -H $EC2_IP >> ~/.ssh/known_hosts
      - run:
          name: SSH into EC2 and Deploy
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_IP \
              "cd d4ad && \
              git pull origin master && \
              ./scripts/install-all.sh && \
              ./scripts/db-migrate.sh && \
              rm -rf backend/dist/ && \
              ./scripts/build.sh"

workflows:
  deploy:
    jobs:
      - deploy_dev:
            